### ISSUE TITLE
Better Discord

### ISSUE THREAD

**Issue by yofukashino** [Faelayis/RPC-Pc-Status#2]
**Is your feature request related to a problem? Please describe.**
no its not a problem i guess
**Describe the solution you'd like**
i want this as a better discord plugin, its a way of distribution too, make a better discord plugin of this. it would be more efficient on for cpu too.
**Describe alternatives you've considered**
nah there aint anything else i thought
**Additional context**
better discord is a discord mod which enables you to add plugins to it. it would be nice if you can make a plugin for this. better discord have a [plugin for rpc](https://betterdiscord.app/plugin/AutoStartRichPresence) but its just static rpc, i want my pc status there, it would be nice if you can make it.

**Comment by Faelayis** [comment]
Coming soon in beta version

**Comment by Faelayis** [comment]
Pre-release https://github.com/Faelayis/RPC-Pc-Status-BetterDiscord

**Comment by yofukashino** [comment]
Thanks

**Comment by Faelayis** [comment]
I don't know if it works well, i tested in discord canary only

**Comment by yofukashino** [comment]
Every thing else work else then rpc injection thingy
